# 网站图标
favicon:
  enable: true
  icon: /images/favicon.png
  touch_icon: /images/favicon.png

# 用户头像与昵称
avatar:
  author_photo: /images/avatar.png
  author_nickname: Vastiny
  path: /

# 页脚信息
footer:
  -
    name: Copyright © Vastiny 2026 :P
    path: https://vastiny.com
  -
    name: Theme by Leedom | Powered by Hexo
    path: https://github.com/leedom92/hexo-theme-leedom

link:
  -
    name: twitter
    icon: twitter
    path: https://twitter.com/ivastiny
    target: _blank
  -
    name: github
    icon: github
    path: https://github.com/yantze
    target: _blank

google_analytics: G-WJ1ZY9QR8J
